apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
    kustomize.toolkit.fluxcd.io/name: vote
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: db
  namespace: instavote
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db
  type: ClusterIP
status:
  loadBalancer: {}