apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    kustomize.toolkit.fluxcd.io/name: vote
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: redis
  namespace: instavote
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
status:
  loadBalancer: {}